trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*

pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      
resources:
  containers:
  - container: nv-bionic-wasm
    image: nventive/wasm-build:1.5

jobs:
- template: build/ci/.azure-devops-windows.yml
- template: build/ci/.azure-devops-docs.yml
- template: build/ci/.azure-devops-wasm-uitests.yml
- template: build/ci/.azure-devops-macos.yml
- template: build/ci/.azure-devops-android-tests.yml
- template: build/ci/.azure-devops-ios-tests.yml
- template: build/ci/.azure-devops-screenshot-compare.yml
